################################################################
# 基础配置
################################################################

name = "go-web-skeleton"
debug = false
timezone = "PRC"
defKey = "def value"
httpPort = 59440

[lang]
langDir = "resource/lang"
allowed = "en:English|zh-CN:简体中文"
default = "en"

[log]
logFile = "/data/logs/{hostname}_apt_application-{date}.log"
errFile = "/data/logs/{hostname}_apt_error-{date}.log"
sqlLog = "/data/logs/{hostname}_apt_sql-{date}.log"

[db]
#disable = true
host = "127.0.0.1"
port = 3306
name = "db_test"
user = "root"
password = "123456"
maxIdleConn = 1024
maxOpenConn = 200

[mgo]
disable = true
servers = "127.0.0.1:3717,127.0.0.2:3717"
uri = "/admin?replicaSet=mgset-1234"
auth = "root:123456"
database = "mydb"
connectTimeoutMS = 10000

[cache]
disable = true
db = 1
auth = "123456"
server = "127.0.0.1:6379"
prefix = "cache"

[redis]
disable = true
db = 2
auth = "123456"
server = "127.0.0.1:6379"

# eureka server
[eureka]
servers = "127.0.0.1:4567,172.19.78.195:9030"
username = "user"
password = "pwd"
